apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: common-managed-cert
  namespace: argocd
spec:
  domains:
    - argocd-nghieptb-gke-lab.webapp01.hblab.dev
    - frontend-app-nghieptb-gke-lab.webapp01.hblab.dev