apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-gke-frontend
  namespace: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lab-gke-frontend
  template:
    metadata:
      labels:
        app: lab-gke-frontend
    spec:
      containers:
      - name: mycontainer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
          name: http