apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-gke-frontend
  namespace: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: lab-gke-frontend
      app.kubernetes.io/instance: lab-gke-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab-gke-frontend
        app.kubernetes.io/instance: lab-gke-frontend
    spec:
      containers:
      - name: mycontainer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 80