apiVersion: v1
kind: Service
metadata:
  name: lab-gke-frontend
  namespace: argocd
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: lab-gke-frontend
    app.kubernetes.io/instance: lab-gke-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http # Phải khớp với name: http trong Deployment