apiVersion: v1
kind: Service
metadata:
  name: lab-gke-frontend-svc
  namespace: argocd
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lab-gke-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 