replicaCount: 1

appName: lab-gke-frontend
namespace: argocd # Để cùng namespace với ArgoCD cho tiện quản lý ban đầu

image:
  repository: us-central1-docker.pkg.dev/lab-gke-485602/lab-gke-485602-dev-registry/frontend-api
  tag: v1.0.1

ingress:
  enabled: false # Tắt đi nếu bạn chưa dùng ingress riêng cho app này
  hosts:
    - host: frontend-app-nghieptb-gke-lab.webapp01.hblab.dev
      paths:
        - path: /
          pathType: ImplementationSpecific



service:
  type: ClusterIP
  port: 80

configmap:
  name: myhelmapp-configmap-v1

  data:
    CUSTOM_HEADER: "Welcome to GKE Lab of NghiepTB"