replicaCount: 1

appName: frontend-app
namespace: argocd # Để cùng namespace với ArgoCD cho tiện quản lý ban đầu

image:
  repository: devopsjourney1/mywebapp
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false # Tắt đi nếu bạn chưa dùng ingress riêng cho app này
  hosts:
    - host: frontend-app-nghieptb-gke-lab.webapp01.hblab.dev
      paths:
        - path: /
          pathType: ImplementationSpecific



service:
  type: ClusterIP
  port: 80

configmap:
  name: myhelmapp-configmap-v1

  data:
    CUSTOM_HEADER: "Welcome to GKE Lab"