apiVersion: v1
kind: ConfigMap
metadata:
  # Đặt tên động theo tên Release của Helm
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.database.name }};
    USE {{ .Values.database.name }};
    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        content VARCHAR(255) NOT NULL
    );
    INSERT INTO messages (content) VALUES ('Xin chào! Đây là dữ liệu được lấy từ MySQL Database qua Backend API.');

    CREATE TABLE IF NOT EXISTS photos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gcs_object_name VARCHAR(255) NOT NULL, -- Tên file trên GCS, vd: 'ky-niem-da-lat-1.jpg'
    caption VARCHAR(500),                  -- Lời nhắn cho bức ảnh
    date_taken DATE,                       -- Ngày chụp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    -- 1. Chuyển đổi Database sang utf8mb4
    ALTER DATABASE appdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- 2. Chuyển đổi bảng photos sang utf8mb4
    ALTER TABLE photos CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- 3. Đảm bảo cột caption dùng đúng bảng mã
    ALTER TABLE photos MODIFY caption VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    INSERT INTO photos (gcs_object_name, caption, date_taken) 
    VALUES ('demo-anh-1.jpg', 'Ngày đầu tiên hẹn hò ❤️', '2025-07-06');