apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-secret
spec:
  refreshInterval: "1h" # Cứ 1 tiếng ESO sẽ check GCP xem mật khẩu có đổi không
  secretStoreRef:
    name: {{ .Release.Name }}-gcp-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-db-secret # Đây là tên K8s Secret thực tế sẽ được tạo ra
    creationPolicy: Owner
  data:
  - secretKey: mysql-password # Tên key lưu trong K8s Secret
    remoteRef:
      key: {{ .Values.dbSecretKey }} # Tên của Secret trên Google Cloud Secret Manager