apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.clusterLocation | quote }}
          clusterName: {{ .Values.gcp.clusterName | quote }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.email }} # Sử dụng ServiceAccount vừa tạo bên trên