apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    # Gắn kết với GCP Service Account đã tạo ở Bước 2
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.email }}