apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lab-gke-backend.fullname" . }}
data:
  # This is the configuration for the backend application, you can add any configuration you want here and it will be mounted to the backend application as a file.
  # For more information on ConfigMap, please check here: https://kubernetes.io/docs/concepts/configuration/configmap/
  config.yaml: |-
    database:
      host: {{ include "lab-gke-database.fullname" . }}
      port: {{ .Values.database.port }}
      username: {{ .Values.database.username }}
      password: {{ .Values.database.password }}