# Cấu hình Health Check cho GKE Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: backend-api
  annotations:
    # Báo cho GKE Load Balancer dùng cấu hình Health Check ở trên
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backend-config"}'
    # Bật tính năng NEG (Network Endpoint Group) định tuyến trực tiếp đến Pod
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}