# Cấu hình Health Check cho GKE Load Balancer
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: backend-api
spec:
  healthCheck:
    checkIntervalSec: 15
    port: {{ .Values.service.port }}
    type: HTTP
    requestPath: {{ .Values.service.healthCheckPath }} # API Node.js của bạn phải trả về 200 OK ở path này

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: backend-api
  annotations:
    # Báo cho GKE Load Balancer dùng cấu hình Health Check ở trên
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backend-config"}'
    # Bật tính năng NEG (Network Endpoint Group) định tuyến trực tiếp đến Pod
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: backend-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}